/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_FTM2CH1SRC_FTM 0x00u     /*!<@brief FTM2 channel 1 input capture source select: FTM2_CH1 signal */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (coord E10), U7[4]/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 16U    /*!<@brief PORTB pin index: 16 */
                                                /* @} */

/*! @name PORTB17 (coord E9), U10[1]/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 17U    /*!<@brief PORTB pin index: 17 */
                                                /* @} */

/*! @name PORTA12 (coord K9), U13[12]/RMII0_RXD1
  @{ */
#define BOARD_INITPINS_RMII0_RXD1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_RXD1_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                             /* @} */

/*! @name PORTA13 (coord J9), U13[13]/RMII0_RXD0
  @{ */
#define BOARD_INITPINS_RMII0_RXD0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_RXD0_PIN 13U    /*!<@brief PORTA pin index: 13 */
                                             /* @} */

/*! @name PORTA14 (coord L10), U13[15]/RMII0_CRS_DV
  @{ */
#define BOARD_INITPINS_RMII0_CRS_DV_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_CRS_DV_PIN 14U    /*!<@brief PORTA pin index: 14 */
                                               /* @} */

/*! @name PORTA15 (coord L11), U13[19]/RMII0_TXEN
  @{ */
#define BOARD_INITPINS_RMII0_TXEN_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_TXEN_PIN 15U    /*!<@brief PORTA pin index: 15 */
                                             /* @} */

/*! @name PORTA16 (coord K10), U13[20]/RMII0_TXD_0
  @{ */
#define BOARD_INITPINS_RMII0_TXD_0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_TXD_0_PIN 16U    /*!<@brief PORTA pin index: 16 */
                                              /* @} */

/*! @name PORTA17 (coord K11), U13[21]/RMII0_TXD_1
  @{ */
#define BOARD_INITPINS_RMII0_TXD_1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_TXD_1_PIN 17U    /*!<@brief PORTA pin index: 17 */
                                              /* @} */

/*! @name PORTA5 (coord M8), U13[17]/RMII0_RXER
  @{ */
#define BOARD_INITPINS_RMII0_RXER_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_RXER_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                             /* @} */

/*! @name PORTB0 (coord H10), U13[10]/RMII0_MDIO
  @{ */
#define BOARD_INITPINS_RMII0_MDIO_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RMII0_MDIO_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                             /* @} */

/*! @name PORTB1 (coord H9), U13[11]/RMII0_MDC
  @{ */
#define BOARD_INITPINS_RMII0_MDC_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RMII0_MDC_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                            /* @} */

/*! @name PORTC9 (coord D7), LEDRGB_RED
  @{ */
#define BOARD_INITPINS_LED_RED_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_RED_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                          /* @} */

/*! @name PORTE6 (coord E1), LEDRGB_GREEN
  @{ */
#define BOARD_INITPINS_LED_GREEN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED_GREEN_PIN 6U     /*!<@brief PORTE pin index: 6 */
                                            /* @} */

/*! @name PORTA11 (coord L9), LEDRGB_BLUE
  @{ */
#define BOARD_INITPINS_LED_BLUE_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LED_BLUE_PIN 11U    /*!<@brief PORTA pin index: 11 */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
